spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/starter
    username: starter
    password: starter
#  flyway:
#    url: jdbc:postgresql://localhost:5432/core
#    user: core
#    password: core
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/core
#    username: core
#    password: core