server:
  port: ${PORT:8080}

spring:
  application:
    name: Core
  banner:
    location: banner/nyan.txt
  codec:
    max-in-memory-size: 5MB
#  flyway:
#    enabled: true
#    locations: classpath:/flyway
#    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    user: ${DB_USER}
#    password: ${DB_PASSWORD}
#  jpa:
#    open-in-view: false
#    generate-ddl: false
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: validate
#  r2dbc:
#    url: r2dbc:postgresql://${DB_HOST}:5432/${DB_NAME}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
  main:
    web-application-type: REACTIVE

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html